url: https://custartupcapstone.com
baseurl: ""

# Site settings
title: CU Boulder Startup Capstone
email: ""
description: "2017 Computer Science Entrepreneurial Capstone at the University of Colorado Boulder"


# Team names, titles and social links
people:
- name: Professor Rick Han
  pic: rick
  position: Associate Professor - Department of Computer Science
  social:
    - title: link
      url: https://www.cs.colorado.edu/~rhan/

- name: Zach Nies
  pic: zach
  position: VP of Education - Techstars
  social:
    - title: twitter
      url: https://twitter.com/zachnies?lang=en
    - title: linkedin
      url: https://www.linkedin.com/in/zachnies

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/CUStartupCapstone

# Build settings
markdown: kramdown
permalink: pretty
